import Vue from 'vue'
import App from './App.vue'
import router from './router'
import VeeValidate from 'vee-validate'
//import axios from 'axios'
import localStorage from 'vue-localstorage'

Vue.config.productionTip = false
Vue.use(VeeValidate);
/* eslint-disable */

Vue.use(localStorage);

export var localstore = {
	user:{
		token:'',
		user_id:'',
		name:'',
		email:'',
		country:'',
		mobile:'',
		rewards:'',
		alternate_email:''
	},
	details:{
		token:'',
		user_id:'',
		property_id:1,
		landlord_id:1,
		document_id:1,
		Property_name:'',
		Security_deposit_amount:'',
		Rent_amount:'',
		Maintenance_amount:'',
		Maintenance_due_date:'',
		Rent_due_date:'',
		Staying_since:'',
		deposit:'',
		property_image:'',
		property_image_name:'',
		Door_number:'',
		Society:'',
		Area:'',
		City:'',
		State:'',
		Pin:'',
		Landlord_name:'',
		Account_holder_name:'',
		Bank_name:'',
		IFSC:'',
		Account_number:'',
		Landlord_city:'',
		Landlord_state:'',
		Landlord_PAN_number:'',
		pan_doc:'',
		pan_doc_name:'',
		startdate_agreement:'',
		enddate_agreement:'',
		rent_agreement:'',
		rent_agreement_name:'',
		M_same:'',
		M_Account_holder_name:'',
		M_Bank_name:'',
		M_IFSC:'',
		M_Account_number:'',
	},
	transaction:{
		ID:'',
		mode_of_payment:'',
		date:'',
		rent_month:'',
		rent_amount:'',
		rent_year:'',
		remarks:'',
	},
	IFSCcodes:{
		"Allahabad Bank":"ALLA",
		"Andhra Bank":"ANDB",
		"Axis Bank":"UTIB",
		"Bank of Baroda":"BARB",
		"Bank of India":"BKID",
		"Bank of Maharashtra":"MAHB",
		"Bank of Punjab":"PUNB",
		"Bank of Rajasthan":"BRAJ",
		"BNP Paribas":"BNPA",
		"Canara Bank":"CNRB",
		"Central Bank of India":"CBIN",
		"Centurion Bank":"CENT",
		"Corporation Bank":"CORP",
		"Citi Bank":"CITI",
		"City Union Bank":"CIUB",
		"Catholic Syrian Bank":"CSBK",
		"DCB Bank":"DCBL",
		"Development Credit Bank":"DCBL",
		"Deutsche Bank AG":"DEUT",
		"Dhanlakshmi Bank":"DLXB",
		"Dena Bank":"BKDN",
		"Federal Bank":"FDRL",
		"HDFC Bank":"HDFC",
		"HSBC Bank":"HSBC",
		"ICICI Bank":"ICIC",
		"IDBI Bank":"IBKL",
		"Indian Bank":"IDIB",
		"Indian Overseas Bank":"IOBA",
		"IndusInd Bank":"INDB",
		"ING Vysya Bank":"VYSA",
		"Jammu &amp; Kashmir Bank":"JAKA",
		"Karnataka Bank":"KARB",
		"Kotak Mahindra Bank":"KKBK",
		"Karur Vysya Bank":"KVBL",
		"Lakshmi Vilas Bank":"LAVB",
		"NKGSB Co-operative Bank Ltd":"NKGS",
		"Oriental Bank of Commerce":"ORBC",
		"PunjabSind Bank":"PSIB",
		"Punjab National Bank":"PUNB",
		"Standard Chartered Bank":"SCBL",
		"State Bank of India":"SBIN",
		"State Bank of Indore":"SBIN",
		"State Bank of Mysore":"SBIN",
		"State Bank of Patiala":"SBIN",
		"State Bank of Travancore":"SBIN",
		"State Bank of Bikaner and Jaipur":"SBIN",
		"State Bank of Hyderabad":"SBIN",
		"State Bank of Saurashtra":"SBIN",
		"South Indian Bank":"SIBL",
		"Syndicate Bank":"SYNB",
		"UCO Bank":"UCBA",
		"UTI Bank":"UTIB",
		"Union Bank of India":"UBIN",
		"United Bank of India":"UTBI",
		"United Western Bank":"UWBK",
		"Vijaya Bank":"VIJB",
		"Yes Bank":"YESB"
	},

	acclength:{
		"Andhra Bank":[15],
		"Allahabad Bank":[11],
		"Axis Bank":[15],
		"Bank of Baroda":[14],
		"Bank of India":[15],
		"Bank of Maharashtra":[11],
		"Canara Bank":[13],
		"Central Bank of India":[10],
		"Corporation Bank":[15],
		"Catholic Syrian Bank":[18],
		"Dhanlakshmi Bank":[16],
		"Dena Bank":[12],
		"Federal Bank":[14],
		"HDFC Bank":[14],
		"ICICI Bank":[12],
		"IDBI Bank":[13,14,15,16],
		"Indian Bank":[9,10,11,12,13,14,15,16,17],
		"Indian Overseas Bank":[15],
		"IndusInd Bank":[13],
		"Jammu &amp; Kashmir Bank":[16],
		"Karnataka Bank":[1],
		"Kotak Mahindra Bank":[10,14],
		"Oriental Bank of Commerce":[14],
		"Punjab National Bank":[16],
		"PunjabSind Bank":[14],
		"Standard Chartered Bank":[11],
		"State Bank of Indore":[11],
		"State Bank of Travancore":[11],
		"State Bank of Bikaner and Jaipur":[11],
		"State Bank of Hyderabad":[11],
		"State Bank of Saurashtra":[11],
		"South Indian Bank":[16],
		"Syndicate Bank":[14],
		"Tamilnadu Mercantile Bank":[6,7,8,9,10,11,12,13,14,15],
		"Union Bank of India":[15],
		"UCO Bank":[14],
		"Vijaya Bank":[15],
		"Yes Bank":[15]
	},

	startdig:{
		"State Bank of Indore":[53,63],
		"State Bank of Travancore":[57,67],
		"State Bank of Hyderabad":[5,6],
		"State Bank of Saurashtra":[56,66],
	}
}

new Vue({
  		router,


  		render: h => h(App)
	}).$mount('#app')
